/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.pt1.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
