/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<Personagem> personagem = new ArrayList<>();

        personagem.add(new Aldeao(25,1,0.8));
        personagem.add(new Arqueiro(35,2,1));
        personagem.add(new Cavaleiro(50,3,2));

        System.out.println(personagem.get(0).atacar());
        System.out.println(personagem.get(1).atacar());
        System.out.println(personagem.get(2).atacar());

        System.out.println(personagem.get(0).mover());
        System.out.println(personagem.get(1).mover());
        System.out.println(personagem.get(2).mover());


    }
}
