/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.animais.*;
import engtelecom.poo.animais.tipos.*;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        ArrayList<Animal> animais = new ArrayList<>(3);

        animais.add(new Arara("Jade"));
        animais.add(new Morcego("Mango"));
        animais.add(new Pinguim("Juca"));
        animais.add(new Ornitorinco("Guerra"));
        animais.add(new Leao("Simba"));
        animais.add(new Baleia("Juca junior"));

        for (Animal animal : animais) {
            if(animal instanceof Voador){
                System.out.println(((Voador) animal).voar());
            }
            if (animal instanceof Mamifero) {
                System.out.println(((Mamifero) animal).morder());
            }
            if (animal instanceof Terrestre) {
                System.out.println(((Terrestre) animal).correr());
            }
            if (animal instanceof Nadador) {
                System.out.println(((Nadador) animal).nadar());
            }
            if (animal instanceof Oviparo) {
                System.out.println(((Oviparo) animal).botarOvo());
            }
        }
    }
}
