/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.pt1;

public class App {
    public static void main(String[] args){
       Pilha<String> pilha = new Pilha<>(5);
       String[] palavras = new String[5];

       palavras[0] = "Olá";
       palavras[1] = "Daniel";
       palavras[2] = "Seja";
       palavras[3] = "Bem";
       palavras[4] = "Vindo";

       for(String p : palavras){
            try {
                pilha.empilhar(p);
            }catch (PilhaCheiaException e) {
                System.err.print("Erro: " + e.getMessage());
            }
       }

       System.out.println("Elemento do topo: ");
       try {
           System.out.println(" " + pilha.elementoTopo());
       } catch (PilhaVaziaException e) {
           System.err.println("Erro: " + e.getMessage());
       }

//        try {
//            pilha.empilhar("Daniel Fernandes");
//        }catch (PilhaCheiaException e) {
//            System.err.print("Erro: " + e.getMessage());
//        }

        for (int i = 0; i < 6 ; i++) {
            try {
                pilha.desempilhar();
            } catch (PilhaVaziaException e) {
                System.err.println("Erro: " + e.getMessage());
            }
        }




    }
}
