/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.pt1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        try(Scanner arq = new Scanner(App.class.getClassLoader().getResourceAsStream("produtos.txt"))) {
            while (arq.hasNext()){
                System.out.println(arq.nextLine());
            }
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }

    }

}
