/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Carro c = new Carro(10002, 20);
        System.out.println(c.getIdentificacao());
        System.out.println(c.getVelocidade());
        c.acelerar(80);
        System.out.println(c.getVelocidade());
        c.acelerar(100);
        System.out.println(c.getVelocidade());
        c.acelerar(40);
        System.out.println(c.getVelocidade());
        c.frear(100);
        System.out.println(c.getVelocidade());
        c.frear(100);
        System.out.println(c.getVelocidade());


    }
}
