/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;

public class App {

    public static void main(String[] args) {
        Draw draw = new Draw("Daniel");

//        draw.clear(Color.LIGHT_GRAY);
//        draw.setPenColor(Color.BLUE);
//
//        draw.filledSquare(.5,.5,.1);
//        draw.rectangle(.5,.5,100,100);
//
//        draw.setPenColor(Color.ORANGE);
//        draw.text(.4,.4,"Daniel - IFSC");
//
//        draw.setPenRadius(.3);
//        draw.line(.10, .10, .5,.5);
        draw.setCanvasSize(1000,600);
        draw.setXscale(0, 500);
        draw.setYscale(0, 500);

        draw.setPenColor(Color.CYAN);
        draw.filledSquare(250,250,100);
        draw.picture(250,250, "bananaDePijama.png");
    }
}
