/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Horario h = new Horario(23,10,58);
        Horario h1 = new Horario(2, 56, 14);
        System.out.println(h);
        System.out.println(h.escreveHorario());
        System.out.println(h.horarioSegundos());
        System.out.println(h.diferencaHorarios(h1));
    }
}
