/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.checkerframework.checker.units.qual.A;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    //CLASSE APP: BANCO DE DADOS DE AUTORES, E UM BANCO DE DADOS DE LIVROS
    //CLASSE APP: Todos os livros estarão em um banco de DADOS

//    private ArrayList<Autor> autores;
//    private ArrayList<Livro> livros;
//
//    public App(){
//        this.autores = new ArrayList<>();
//        this.livros  = new ArrayList<>();
//    }
//
//    public boolean addAutor(Autor autor){
//        return this.autores.add(autor);
//    }
//
//    public boolean addLivro(String isbn, String titulo, Autor[] autores){
//        ArrayList<Autor> aux = new ArrayList<>(Arrays.asList(autores));
//        return this.livros.add(new Livro(isbn, titulo, aux));


    private Carro carro;

    public static void main(String[] args) {
        Carro civic =  new Carro("civic", "branco", new Motor("0154-f", 800, 8));
        System.out.println(civic);
        civic.setMotor(new Motor("0124-h", 1000, 16));
        System.out.println(civic);
    }
}
