/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.pt1;

import java.util.InputMismatchException;
import java.util.Scanner;




public class App {

    public static void main(String[] args) {
        Scanner ler = new Scanner(System.in);
        int a, b;

        System.out.println("Iniciando");
        try{
            System.out.println("Entre com o primeiro valor: ");
            a = ler.nextInt();
            System.out.println("Entre com o segundo valor: ");
            b = ler.nextInt();

            double res = (double) a / b;

            System.out.println(a + " dividido por " + b + " = " + res);
        } catch (InputMismatchException e){
            System.err.println("Só é permitido números inteiros");
            ler.nextLine();
        } catch( ArithmeticException e){
            System.err.println("Não é permitido divisões por 0");
            ler.nextLine();
        } catch( Exception e){
            System.err.println("Comportamento inesperado");
            ler.nextLine();
        }
        System.out.println("Finalizando");
    }

}
