/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.produtos.SemFio;
import engtelecom.poo.produtos.Telefone;

public class App {
    public static void main(String[] args) {
        Dimensao dimensoesTelefoneUm = new Dimensao(0.3,0.3,0.8);
        Telefone telefoneUm = new Telefone(1001,"AS-103", "Retrô", "Preto", 14.5,  dimensoesTelefoneUm);
        System.out.printf(telefoneUm.toString());
        System.out.println("\n");
        SemFio telefoneDois = new SemFio(1002, "NS-152", "Moderno", "Azul",5.0,dimensoesTelefoneUm, 2.4,12,25.0);
        System.out.printf(telefoneDois.toString());

    }
}
