/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        Pessoa p = new Pessoa("Daniel");
        Estudande e = new Estudande("Juca", "092");
        Carro c = new Carro("civic");

//        Caixa caixa = new Caixa();
//
//        caixa.setConteudo(e);
//        caixa.setConteudo(c);
//        caixa.setConteudo(p);
//
//        Carro outro = (Carro) caixa.getConteudo();
//        System.out.println(outro);
//
//        Caixa<Carro> caixa = new Caixa<>();
//        caixa.setConteudo(c);
//
//        ArrayList<Carro> carros = new ArrayList<>();
//
        Caixa<Pessoa> caixa = new Caixa<>();
        caixa.setConteudo(p);
        caixa.setConteudo(e);
    }
}
