/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Retangulo r = new Retangulo(10, 10, "UTF-8");
        System.out.println(r);
    }
}
